In [106]:
import h5py
import numpy as np

In [114]:
with h5py.File('../../data/yse.hdf5') as f:
    classes  = f['spec_class'][:]
arg_keep = np.where(classes != b'NA')

with h5py.File('../../data/yse.hdf5') as f:
    flux     = f['flux'][arg_keep]
    time     = f['time'][arg_keep]
    photo_z  = f['photo_z'][arg_keep]
    classes  = f['spec_class'][arg_keep]
    print(f.keys())

n_objects = flux.shape[0]
data   = np.stack([time, flux], axis=2).reshape(n_objects, -1)
data   = np.concatenate([data, photo_z[:, None]], axis=1)

type_classes = np.unique(classes)
n_classes    = len(type_classes)
class_dict   = dict(zip(type_classes, np.arange(0, n_classes)))
labels       = np.array([class_dict[c] for c in classes])

<KeysViewHDF5 ['dec', 'flux', 'flux_err', 'host_log_mass', 'object_id', 'photo_z', 'quality_mask', 'ra', 'redshift', 'spec_class', 'spec_class_broad', 'time']>


In [132]:
with h5py.File('../../data/yse.hdf5') as f:
    flux     = f['flux'][:]
    time     = f['time'][:]
    photo_z  = f['photo_z'][:]
    classes  = f['spec_class'][:]
    print(f.keys())

<KeysViewHDF5 ['dec', 'flux', 'flux_err', 'host_log_mass', 'object_id', 'photo_z', 'quality_mask', 'ra', 'redshift', 'spec_class', 'spec_class_broad', 'time']>


In [137]:
class_dict

{b'LBV': 0,
 b'LRN': 1,
 b'Other': 2,
 b'SLSN-I': 3,
 b'SLSN-II': 4,
 b'SN': 5,
 b'SN-II': 6,
 b'SN-IIb': 7,
 b'SN-IIn': 8,
 b'SN-Ia-91T-like': 9,
 b'SN-Ia-91bg-like': 10,
 b'SN-Ia-CSM': 11,
 b'SN-Ia-SC': 12,
 b'SN-Ia-norm': 13,
 b'SN-Iax': 14,
 b'SN-Ib': 15,
 b'SN-Ib-pec': 16,
 b'SN-Ibn': 17,
 b'SN-Ic': 18,
 b'SN-Ic-BL': 19,
 b'TDE': 20}

In [133]:
np.unique( labels )

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [134]:
np.unique(classes)

array([b'LBV', b'LRN', b'NA', b'Other', b'SLSN-I', b'SLSN-II', b'SN',
       b'SN-II', b'SN-IIb', b'SN-IIn', b'SN-Ia-91T-like',
       b'SN-Ia-91bg-like', b'SN-Ia-CSM', b'SN-Ia-SC', b'SN-Ia-norm',
       b'SN-Iax', b'SN-Ib', b'SN-Ib-pec', b'SN-Ibn', b'SN-Ic',
       b'SN-Ic-BL', b'TDE'], dtype='|S50')

In [93]:
data.shape

(494, 1753)

In [77]:
class_dict

{b'NA': 0, b'Other': 1, b'SN': 2}

In [72]:
np.where( labels == b'NA' )

(array([   2,    3,    4, ..., 1999, 2000, 2001]),
 array([0, 0, 0, ..., 0, 0, 0]))

In [68]:
labels

array([[b'SN'],
       [b'SN'],
       [b'NA'],
       ...,
       [b'NA'],
       [b'NA'],
       [b'SN']], dtype='|S50')

In [50]:
data.reshape(2003, -1).shape

(2003, 1752)

In [42]:
data.shape, labels.shape

((2003, 6, 2, 146), (2003, 1))

In [24]:
flux.shape

(2003, 6, 146)

In [26]:
np.unique(labels)

array([b'LBV', b'LRN', b'NA', b'Other', b'SLSN-I', b'SLSN-II', b'SN',
       b'TDE'], dtype='|S50')

In [27]:
np.unique(labels_broad)

array([b'NA', b'Other', b'SN'], dtype='|S50')

In [21]:
( labels_broad != b'SN' ).sum()

1529

In [28]:
( labels_broad == b'NA' ).sum()

1509